# For Installation....
install.packages("dplyr")
library(dplyr) # without installing any library we can't do anything......
# Entering a csv file..
stu <- read.csv("D:/SEMISTER 4/INT232 DATA SCIENCE TOOLBOX - R PRO/PDF/students.csv")
show(stu)
View(stu) # To show the tables head(stu)
# to arrange the data accordingly.....
stu.arrageData<- arrange(stu, marks)
View(stu.arrageData)
filter(stu, marks > 50)
filter(stu, marks %in% c(40, 45)) # %in% works like 'in' operator in Python..


# SELECT function in Dplyr....
# Selct operation only works on columns...
select(stu, name, marks)
select(stu, 1:3) # Column number....
select(stu, name:marks) # Column name calls...
select(stu, -roll_no) # Except roll number Everything will be displayed...
select(stu, starts_with(c("n", "m"))) # Select all the coulmns that starts with n amd m...
# if we put one_if - it means Either col1  or col2
select(stu, contains("R", ignore.case = TRUE))
select(stu, ends_with("s", ignore.case = TRUE))
select(stu, one_of("marks", "roll_no")) # selects the roll and marks column..
select(stu, everything()) # Select all the Columns in the dataFrame...


# Arrange Function in 
arrange(stu, marks) # arrange by marks in accending order...
arrange(stu, roll_no, marks) # arrange by roll_no and than marks...
arrange(stu, desc(roll_no)) # to change the roll_no in descending wise.....


# mutate and rename function in R...
View(mutate(stu, Half_of_marks = ceiling(marks/2)))
# mutate meaning adding new columns based on other column values....
# To rename the column name...
View(rename(stu, Name_of_Student = name))

miningData <- read.csv("")









